import type { MonsterCard } from "@/lib/card_model"; // keeps downloaded filenames tied to the current monster.

export function card_filename(card: MonsterCard, extension: string): string { // preserves one safe naming convention across card exports.
  return `${card.species_id}_${card.species_name}`.replace(/[^a-z0-9_-]/gi, "_").toLowerCase() + `.${extension}`; // removes filesystem-sensitive characters from the filename.
}
export function download_blob(blob: Blob, filename: string): void { // downloads generated bytes without requiring a server-side export file.
  const url: string = URL.createObjectURL(blob); // exposes the complete file to the browser.
  const link: HTMLAnchorElement = document.createElement("a"); // creates the native download action.
  link.href = url; link.download = filename; // associates the file with its descriptive name.
  try { document.body.appendChild(link); link.click(); } // starts the download from the user's selected action.
  finally { link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 60000); } // releases temporary resources after the browser consumes the file.
}
